import {z} from 'zod';
export const eventSchema=z.object({seq:z.number(),kind:z.string(),title:z.string(),detail:z.string(),at:z.string()});
export const ticketSchema=z.object({id:z.string(),subject:z.string(),message:z.string(),orderId:z.string(),scenario:z.string()});
export const runSchema=z.object({id:z.string(),state:z.string(),summary:z.string().default(''),error:z.string().default(''),model:z.string(),promptVersion:z.string(),turns:z.number(),usedMicros:z.number(),inputTokens:z.number().optional(),outputTokens:z.number().optional(),ticket:ticketSchema,order:z.object({id:z.string(),status:z.string(),totalMinor:z.number(),currency:z.string(),address:z.string(),version:z.number()}),events:z.array(eventSchema),evidence:z.array(z.object({id:z.string(),title:z.string(),content:z.string(),version:z.string()})),proposal:z.object({id:z.string(),kind:z.string(),digest:z.string(),amountMinor:z.number(),address:z.string(),reason:z.string(),expires:z.number()}).nullable(),receipt:z.object({id:z.string(),detail:z.string(),simulated:z.boolean()}).nullable()});
export type Run=z.infer<typeof runSchema>;export type Ticket=z.infer<typeof ticketSchema>;
export type Replay={label:string;run:Run;recordedAt:string;commit:string;providerVerified:boolean};
export async function request(path:string,body?:unknown){const response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||data.detail||'Request failed');return data;}
const fields=`id state summary error model promptVersion turns usedMicros inputTokens outputTokens ticket{id subject message orderId scenario} order{id status totalMinor currency address version} events{seq kind title detail at} evidence{id title content version} proposal{id kind digest amountMinor address reason expires} receipt{id detail simulated}`;
async function gql(query:string,variables:Record<string,unknown>={}){const res=await request('/graphql',{query,variables});if(res.errors?.length)throw new Error(res.errors[0].message);return res.data;}
export async function tickets(){return z.array(ticketSchema).parse((await gql('{tickets{id subject message orderId scenario}}')).tickets);}
export async function getRun(id:string){return runSchema.parse((await gql(`query($id:String!){run(id:$id){${fields}}}`,{id})).run);}
export async function startRun(ticketId:string){return runSchema.parse((await gql(`mutation($id:String!){startRun(ticketId:$id){${fields}}}`,{id:ticketId})).startRun);}
export async function changeRun(action:'approve'|'reject'|'clarify'|'cancel'|'resume',id:string,text='',digest=''){return runSchema.parse((await gql(`mutation($id:String!,$text:String!,$digest:String!){${action}Run(id:$id,text:$text,digest:$digest){${fields}}}`,{id,text,digest}))[action+'Run']);}
export async function loadReplays():Promise<Replay[]>{const response=await fetch('/replays/index.json');const index=await response.json();return Promise.all(index.runs.map(async(item:{file:string;label:string})=>{if(!/^\/replays\/[a-z0-9-]+\.json$/.test(item.file))throw new Error('Invalid replay path');const data=await(await fetch(item.file)).json();return {...data,label:item.label,run:runSchema.parse(data.run)};}));}
